In [1]:
import cv2 as cv
import numpy as np
from scipy.signal import argrelextrema
import matplotlib.pyplot as plt
import time

In [2]:
frame=cv.imread('frame.jpg')
# plt.imshow(frame)
frame.shape

(720, 1280, 3)

In [3]:
# 参考　https://qiita.com/code0327/items/c6e468da7007734c897f
# 時計回りで左上から順に角を定義
m = np.empty((4,2))

# 720*1280用
m[0] = [70,100]
m[1] = [1100,90]
m[2] = [1140,620]
m[3] = [50,620]

x_min,x_max=59,859
y_min,y_max=-200,200
width, height = (x_max-x_min,y_max-y_min) # 変形後画像サイズ

marker_coordinates = np.float32(m)
true_coordinates   = np.float32([[0,0],[width,0],[width,height],[0,height]])
# true_coordinates   = np.float32([[x_max,y_min],[x_min,y_min],[x_min,y_max],[x_max,y_max]])
trans_mat = cv.getPerspectiveTransform(marker_coordinates,true_coordinates)
img_trans = cv.warpPerspective(frame,trans_mat,(width, height))
# plt.imshow(img_trans)
print(trans_mat)

[[ 8.01965400e-01  3.08448231e-02 -5.92220603e+01]
 [ 8.00057007e-03  8.24058717e-01 -8.29659116e+01]
 [ 2.00014252e-05  1.12703600e-04  1.00000000e+00]]


In [4]:
print(trans_mat)

[[ 8.01965400e-01  3.08448231e-02 -5.92220603e+01]
 [ 8.00057007e-03  8.24058717e-01 -8.29659116e+01]
 [ 2.00014252e-05  1.12703600e-04  1.00000000e+00]]


In [5]:
pix_x=0
pix_y=0
tmp0,tmp1,tmp2=np.dot(trans_mat,[pix_x,pix_y,1])
print(tmp0,tmp1)

-59.22206028000923 -82.96591160152538


In [6]:
mm_x=width-tmp0+59
mm_y=-height/2+tmp1
print(mm_x,mm_y)

918.2220602800093 -282.96591160152536
